version: '3.3'
services:

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo

  odoo:
    build: .
    command: start
    ports:
      - '80:8069'
      - '443:8071'
    links:
      - postgres:db
    environment:
      - ODOO_ADMIN_PASSWD=odoo
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
