version: '3.3'
services:

  odoo:
    build: .
    command: start
    ports:
      - '80:8069'
      - '443:8072'
    volumes:
      - ./volumes/odoo/filestore:/opt/odoo/data/filestore
      - ./volumes/odoo/sessions:/opt/odoo/data/sessions
    environment:
      - TARGET_UID=1000
      - ODOO_ADMIN_PASSWD=odoo
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=odoo
